version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
on:
  pull_request:
    types: [opened, closed, synchronize, merged]

jobs:
deploy_beta:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION_NAME
      - run: >-
          aws s3 cp index.html s3://luit-gold-beta/index.html --acl public-read

deploy_prod:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION_NAME
      - run: >-
          aws s3 cp index.html s3://luit-gold-prod/index.html --acl public-read

workflows:
    jobs:
      - deploy_beta
      - deploy_prod:
          requires:
            - deploy_beta
          filters:
            branches:
              only:
                - main